//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appalonov_Exam.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prog9Entities : DbContext
    {
        public prog9Entities()
            : base("name=prog9Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<OrdersPhone> OrdersPhone { get; set; }
        public virtual DbSet<Phones> Phones { get; set; }
        public virtual DbSet<PhonesType> PhonesType { get; set; }
        public virtual DbSet<RepairPhones> RepairPhones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Typecrash> Typecrash { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
