//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appalonov_Exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersPhone
    {
        public int id_Order { get; set; }
        public int id_Phone { get; set; }
        public Nullable<int> id_User { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
    
        public virtual Phones Phones { get; set; }
        public virtual Users Users { get; set; }
    }
}
